name: Build

on:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
      - "*.yml"
  pull_request:
    paths-ignore:
      - '.github/*'
      - '*.md'
      - "*.yml"
  workflow_dispatch:
    # allow manual trigger

jobs:
  build:
    uses: ServerEmus/workflows/.github/workflows/build.yml@main
    with:
      ProjName: Shared
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN   }}